### ISSUE TITLE
Installation with cargo fails for version 0.6.2

### ISSUE THREAD

**Issue by jonasbb** [igor-petruk/scriptisto#21]
## Expected Behavior
Installation should succeed without error.

## Actual Behavior
Installation with `cargo install` fails with error message:

```
error[E0599]: no function or associated item named `new` found for type `scrawl::editor::Editor<_>` in the current scope
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/scriptisto-0.6.2/src/templates.rs:246:46
    |
246 |     let mut editor = scrawl::editor::Editor::new();
    |                                              ^^^ function or associated item not found in `scrawl::editor::Editor<_>`

error: aborting due to previous error
```

## Steps to Reproduce the Problem

1. Run `cargo install scriptisto`

## Specifications

- Version: 0.6.2
- Platform: Fedora Linux

**Comment by iho** [comment]
+1

**Comment by igor-petruk** [comment]
Thank you for reporting and sorry for the delay. I've pinned a version of scrawl, that changed it's API.  I am publishing the binary

I could have just fix the API. But then I'd have to bump scrawl in Debian. I think I might do in the following days. Now let's just fix the issue
