### ISSUE TITLE
Add package to Homebrew

### ISSUE THREAD

**Issue by NightMachinery** [igor-petruk/scriptisto#24]
Installing it via `cargo` is quite slow. Having a ready binary is much better. Homebrew supports both macOS and linux.

**Comment by igor-petruk** [comment]
I don't really have a Mac, is it possible to prepare such package from Linux? PR or tips are welcome

**Comment by igor-petruk** [comment]
In addition, I've never tested the tool on Mac. I can try add a recipe for Linux and see where to go from there

**Comment by NightMachinary** [comment]
It seemed to work fine on my mac machine. Since Homebrew works on Linux, too, I assume it should be possible to do this on Linux.

**Comment by igor-petruk** [comment]
Brew might work, but I need to produce a pre-built binary. 

Example: https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep-bin.rb#L7

It references an archive with a static installable binary. But I build my binaries on drone.io in Docker. I need to figure out how to automate Mac OS X builds in the cloud.

**Comment by jayvdb** [comment]
GitHub Actions support MacOS.

**Comment by igor-petruk** [comment]
I've made a tap with pre-built packages:

```console
$ brew install igor-petruk/tap/scriptisto
```

It currently uses packages from the release page and they are built on Github Action runners: Linux musl-based static binary and the binary produced on Mac OS X 12. 

I haven't yet tested it on Mac and I am interested in trying to publish it to homebrew-core with bottles built for every version of Mac OS X.

**Comment by igor-petruk** [comment]
https://github.com/Homebrew/homebrew-core/pull/121060 is a PR trying to add a Formula to the core

**Comment by igor-petruk** [comment]
Formula added to the core: https://github.com/Homebrew/homebrew-core/blob/master/Formula/scriptisto.rb
