### ISSUE TITLE
EndOfStream error when running v0.6.13

### ISSUE THREAD

**Issue by ngirard** [igor-petruk/scriptisto#28]
Using freshest https://github.com/igor-petruk/scriptisto/releases/download/v0.6.13/scriptisto_0.6.13_amd64.deb on Ubuntu 20.04.

`./tst --version` gives
```sh
Error: EndOfStream

Cannot parse config YAML: 
[]
```
v0.6.10 used to give:
```sh
script 0.1.0
```

**Comment by igor-petruk** [comment]
Everything should work now with 0.6.14, can you pls check and close the bug. Thanks
